"""F02 HTTP dispatch + common failure envelope (WU-02.9).

`apps/api/src/nquiry_api/http/inquiry.py` is a thin adapter. Everything
here returns `(status, body)` with a plain JSON body.

COMMON FAILURE ENVELOPE (19 §29 outcome distinctions, 20 §13): each outcome
kind stays distinct on the wire and in the UI.

| kind | HTTP | meaning |
|---|---|---|
| ok | 200 | query result |
| committed | 200 | governed Command committed; body carries the fresh canonical reread |
| denied | 401/403 | identity or authority/boundary denial (reasonCode from the boundary chain) |
| rejected | 400 | malformed or invalid input: never an authority statement |
| stale | 409 | expected version is no longer current; body carries the current version/state |
| blocked | 422 | a lawful precondition is unmet (e.g. no participant yet) |
| failed_precommit | 409 | proven rollback at the effect gate (nothing committed) |
| indeterminate | 503 | commit outcome cannot be proven; no blind retry |
| not_found | 404 | the named object does not exist in this Workspace |

NETWORK_FAILURE is client-side only (no response).

IDEMPOTENCY TRANSPORT: every F02 Command route requires an
`Idempotency-Key` header holding a UUID, generated by the client once per
logical intent. The key is the Command's `command_id` AND its
`idempotency_key`. A retry of the same intent is therefore the same logical
Command (09 §4.3), and after COMMITTED it returns the committed result
without executing again (14 §27). `UI DEBOUNCE ≠ IDEMPOTENCY`.
"""

from __future__ import annotations

import contextlib
import uuid
from collections.abc import Callable
from datetime import datetime, timezone
from typing import Any

from commit.coordinator import CommitDenied, CommitFailedPrecommit, CommitIndeterminate
from commit.idempotency import (
    IdempotencyAlreadyCommitted,
    IdempotencyIndeterminateBlocked,
    IdempotencyInProgress,
    IdempotencyPayloadCollision,
)
from governance.authority_binding import AuthorityClass
from persistence.command_repository import (
    CommandPayloadConflict,
    CommandTypeMismatch,
    CommandWorkspaceMismatch,
)
from persistence.engine import connect
from persistence.local_auth_repository import SqlAlchemyLocalSessionRepository
from semantic_types.ids import ChallengeId, CommandId, SessionId, UserId, WorkspaceId
from semantic_types.versions import MethodVersion

from application import burst_capture_handler as capture
from application import burst_completion_handler as completion
from application import inquiry_queries as queries
from application import session_control_handler as control
from application.auth_handler import resolve_session
from application.authority_binding_handler import (
    GovernanceRightNotGrantableViaGenericGrant,
    GrantAuthorityBindingDenied,
    GrantScopeInvalid,
    grant_human_authority_binding,
)
from application.challenge_creation_handler import ChallengeCreationDenied, create_challenge
from application.composition import GovernedPorts
from application.session_creation_handler import CreateSessionDenied, create_session

Response = tuple[int, dict[str, object]]

PROTOTYPE_METHOD_KEY = "QUESTION_BURST"
PROTOTYPE_METHOD_VERSION = "1.0"
"""The one pinned prototype method (12 §5: 'One pinned prototype
method/configuration is sufficient'), the same pin the demo seed uses."""


class _Rejected(Exception):
    def __init__(self, reason_code: str) -> None:
        self.reason_code = reason_code
        super().__init__(reason_code)


def _denied(reason: str, status: int = 403) -> Response:
    return status, {"kind": "denied", "reasonCode": reason}


def _rejected(reason: str) -> Response:
    return 400, {"kind": "rejected", "reasonCode": reason}


def _uuid(value: str, field: str) -> uuid.UUID:
    try:
        return uuid.UUID(value)
    except (ValueError, TypeError) as exc:
        raise _Rejected(f"MALFORMED_{field.upper()}") from exc


def _idempotency(key: str | None) -> tuple[CommandId, str]:
    if not key:
        raise _Rejected("IDEMPOTENCY_KEY_REQUIRED")
    command_uuid = _uuid(key, "idempotency_key")
    return CommandId(command_uuid), str(command_uuid)


def _with_actor(
    session_token: str | None, work: Callable[[GovernedPorts, Any], Response]
) -> Response:
    """Runs `work` inside ONE request transaction (committed on clean
    return). Identity only from the verified HttpOnly session."""
    try:
        with connect() as connection:
            principal = resolve_session(
                session_token,
                session_repository=SqlAlchemyLocalSessionRepository(connection),
                now=datetime.now(timezone.utc),
            )
            if principal is None:
                return _denied("NO_VALID_SESSION", 401)
            return work(GovernedPorts(connection), principal)
    except _Rejected as exc:
        return _rejected(exc.reason_code)


def _command_outcome(run: Callable[[], Response]) -> Response:
    """Maps every governed-Command exception to its distinct envelope kind."""
    try:
        return run()
    except _Rejected as exc:
        return _rejected(exc.reason_code)
    except capture.CaptureInputRejected as exc:
        # F03 HD-12: input, never authority. Nothing was stored or altered.
        return _rejected(exc.reason_code)
    except control.SessionVersionStale as exc:
        return 409, {
            "kind": "stale",
            "reasonCode": "STALE_VERSION",
            "expectedVersion": exc.expected,
            "currentVersion": exc.current,
            "currentState": exc.current_state,
        }
    except control.SessionPreconditionUnmet as exc:
        return 422, {"kind": "blocked", "reasonCode": exc.reason_code}
    except (
        control.SessionCommandDenied,
        ChallengeCreationDenied,
        CreateSessionDenied,
        GrantAuthorityBindingDenied,
    ) as exc:
        chain = exc.chain_result
        terminal = chain.proofs[-1] if chain.proofs else None
        return _denied(terminal.reason_code if terminal is not None else "DENIED")
    except CommitDenied as exc:
        reason = exc.boundary_proof.reason_code
        if reason.startswith("STALE_VERSION"):
            return 409, {"kind": "stale", "reasonCode": reason}
        return _denied(reason)
    except (GrantScopeInvalid, GovernanceRightNotGrantableViaGenericGrant) as exc:
        return _rejected(str(exc))
    except control.SessionNotFound:
        return 404, {"kind": "not_found", "reasonCode": "SESSION_NOT_FOUND"}
    except (
        IdempotencyPayloadCollision,
        CommandPayloadConflict,
        CommandTypeMismatch,
        CommandWorkspaceMismatch,
    ):
        # F02 WU-02.12 (FBR-B): the key is the command_id, so any reuse for
        # another payload, Command type or Workspace names a different
        # logical Command (09 §4.3). It is input, not authority: `rejected`.
        return _rejected("IDEMPOTENCY_KEY_REUSED_FOR_DIFFERENT_COMMAND")
    except (IdempotencyInProgress, IdempotencyIndeterminateBlocked):
        return 503, {"kind": "indeterminate", "reasonCode": "PRIOR_ATTEMPT_UNRESOLVED"}
    except CommitFailedPrecommit as exc:
        return 409, {"kind": "failed_precommit", "reasonCode": exc.reason}
    except CommitIndeterminate as exc:
        return 503, {
            "kind": "indeterminate",
            "reasonCode": "COMMIT_OUTCOME_UNPROVEN",
            "blockedTargetRef": str(exc.commit_id.value),
        }


def _query(run: Callable[[], dict[str, object]]) -> Response:
    try:
        return 200, run()
    except queries.QueryDenied as exc:
        return _denied(exc.reason_code)
    except queries.QueryNotFound as exc:
        return 404, {"kind": "not_found", "reasonCode": exc.reason_code}


# --------------------------------------------------------------------------- queries


def dispatch_workspace_overview(*, session_token: str | None, workspace_id: str) -> Response:
    def work(ports: GovernedPorts, principal: Any) -> Response:
        ws = WorkspaceId(_uuid(workspace_id, "workspace_id"))
        return _query(lambda: queries.workspace_overview(ports, principal, ws))

    return _with_actor(session_token, work)


def dispatch_challenge_detail(
    *, session_token: str | None, workspace_id: str, challenge_id: str
) -> Response:
    def work(ports: GovernedPorts, principal: Any) -> Response:
        ws = WorkspaceId(_uuid(workspace_id, "workspace_id"))
        cid = ChallengeId(_uuid(challenge_id, "challenge_id"))
        return _query(lambda: queries.challenge_detail(ports, principal, ws, cid))

    return _with_actor(session_token, work)


def dispatch_session_position(
    *, session_token: str | None, workspace_id: str, session_id: str
) -> Response:
    def work(ports: GovernedPorts, principal: Any) -> Response:
        ws = WorkspaceId(_uuid(workspace_id, "workspace_id"))
        sid = SessionId(_uuid(session_id, "session_id"))
        return _query(lambda: queries.session_position(ports, principal, ws, sid))

    return _with_actor(session_token, work)


# --------------------------------------------------------------------------- commands


def _ident(key: str | None) -> control.CommandIdentity:
    command_id, idem = _idempotency(key)
    base = control.CommandIdentity.fresh(datetime.now(timezone.utc), idem)
    return control.CommandIdentity(
        command_id=command_id,
        attempt_id=base.attempt_id,
        correlation_id=base.correlation_id,
        commit_id=base.commit_id,
        occurred_at=base.occurred_at,
        idempotency_key=idem,
    )


def _actor(principal: Any) -> Any:
    from authority.actor import ActorClass, ActorIdentity

    return ActorIdentity(ActorClass.HUMAN_USER, principal.user_id)


def _frame_text(value: str | None) -> str | None:
    """A Challenge frame field (09 §25) is stored exactly as sent; a missing,
    empty or whitespace-only value means "not provided" (WU-PFC-A1 Case 2)."""
    return value if value is not None and value.strip() else None


def dispatch_create_challenge(
    *,
    session_token: str | None,
    idempotency_key: str | None,
    workspace_id: str,
    title: str,
    description: str | None,
    context: str | None = None,
    desired_outcome: str | None = None,
    constraints: str | None = None,
    stakeholders: str | None = None,
) -> Response:
    def work(ports: GovernedPorts, principal: Any) -> Response:
        ws = WorkspaceId(_uuid(workspace_id, "workspace_id"))
        ident = _ident(idempotency_key)
        if not title or not title.strip():
            raise _Rejected("TITLE_REQUIRED")

        def run() -> Response:
            result = create_challenge(
                ports.connection,
                actor=_actor(principal),
                workspace_id=ws,
                title=title.strip(),
                description=(description or "").strip() or None,
                context=_frame_text(context),
                desired_outcome=_frame_text(desired_outcome),
                constraints=_frame_text(constraints),
                stakeholders=_frame_text(stakeholders),
                command_id=ident.command_id,
                attempt_id=ident.attempt_id,
                correlation_id=ident.correlation_id,
                occurred_at=ident.occurred_at,
                commit_id=ident.commit_id,
                idempotency_key=ident.idempotency_key,
                workspace_repository=ports.workspaces,
                membership_repository=ports.memberships,
                challenge_repository=ports.challenges,
                command_repository=ports.commands,
                audit_repository=ports.audit,
                outbox_repository=ports.outbox,
                commit_repository=ports.commits,
                idempotency_port=ports.idempotency,
            )
            return 200, {"kind": "committed", "challengeId": str(result.challenge_id.value)}

        return _command_outcome(run)

    return _with_actor(session_token, work)


def dispatch_create_session(
    *, session_token: str | None, idempotency_key: str | None, workspace_id: str, challenge_id: str
) -> Response:
    def work(ports: GovernedPorts, principal: Any) -> Response:
        from persistence.challenge_repository import SqlAlchemyChallengeVersionReader

        ws = WorkspaceId(_uuid(workspace_id, "workspace_id"))
        cid = ChallengeId(_uuid(challenge_id, "challenge_id"))
        ident = _ident(idempotency_key)
        # One logical intent -> one Session id: derived from the command id,
        # so a retry cannot create a second Session.
        session_id = SessionId(uuid.uuid5(ident.command_id.value, "session"))

        def run() -> Response:
            # Same intent already committed -> return the same Session.
            with contextlib.suppress(IdempotencyAlreadyCommitted):
                create_session(
                    ports.connection,
                    actor=_actor(principal),
                    workspace_id=ws,
                    challenge_id=cid,
                    session_id=session_id,
                    applied_method_key=PROTOTYPE_METHOD_KEY,
                    applied_method_version=MethodVersion(PROTOTYPE_METHOD_VERSION),
                    command_id=ident.command_id,
                    attempt_id=ident.attempt_id,
                    correlation_id=ident.correlation_id,
                    occurred_at=ident.occurred_at,
                    commit_id=ident.commit_id,
                    idempotency_key=ident.idempotency_key,
                    workspace_repository=ports.workspaces,
                    membership_repository=ports.memberships,
                    challenge_repository=ports.challenges,
                    session_repository=ports.sessions,
                    authority_resolver=ports.resolver,
                    command_repository=ports.commands,
                    audit_repository=ports.audit,
                    outbox_repository=ports.outbox,
                    commit_repository=ports.commits,
                    idempotency_port=ports.idempotency,
                    current_version_reader=SqlAlchemyChallengeVersionReader(
                        ports.connection, challenge_id=cid
                    ),
                )
            return 200, {"kind": "committed", "sessionId": str(session_id.value)}

        return _command_outcome(run)

    return _with_actor(session_token, work)


def dispatch_grant_authority(
    *,
    session_token: str | None,
    idempotency_key: str | None,
    workspace_id: str,
    human_user_id: str,
    authority_class: str,
    scope_type: str,
    scope_id: str,
) -> Response:
    def work(ports: GovernedPorts, principal: Any) -> Response:
        from persistence.workspace_repository import SqlAlchemyWorkspaceVersionReader

        ws = WorkspaceId(_uuid(workspace_id, "workspace_id"))
        holder = UserId(_uuid(human_user_id, "human_user_id"))
        scope = _uuid(scope_id, "scope_id")
        try:
            klass = AuthorityClass(authority_class)
        except ValueError as exc:
            raise _Rejected(f"UNKNOWN_AUTHORITY_CLASS:{authority_class}") from exc
        ident = _ident(idempotency_key)

        def run() -> Response:
            try:
                unit = grant_human_authority_binding(
                    ports.connection,
                    actor=_actor(principal),
                    workspace_id=ws,
                    human_user_id=holder,
                    authority_class=klass,
                    scope_type=scope_type,
                    scope_id=scope,
                    command_id=ident.command_id,
                    attempt_id=ident.attempt_id,
                    correlation_id=ident.correlation_id,
                    occurred_at=ident.occurred_at,
                    commit_id=ident.commit_id,
                    idempotency_key=ident.idempotency_key,
                    workspace_repository=ports.workspaces,
                    membership_repository=ports.memberships,
                    authority_binding_repository=ports.bindings,
                    authority_resolver=ports.resolver,
                    command_repository=ports.commands,
                    audit_repository=ports.audit,
                    outbox_repository=ports.outbox,
                    commit_repository=ports.commits,
                    idempotency_port=ports.idempotency,
                    current_version_reader=SqlAlchemyWorkspaceVersionReader(
                        ports.connection, workspace_id=ws
                    ),
                )
            except IdempotencyAlreadyCommitted:
                return 200, {"kind": "committed", "replayed": True}
            return 200, {"kind": "committed", "commitId": str(unit.commit_id.value)}

        return _command_outcome(run)

    return _with_actor(session_token, work)


_SESSION_COMMANDS: dict[str, Callable[..., Any]] = {
    "begin-setup": control.begin_setup,
    "begin-challenge-capture": control.begin_challenge_capture,
    "open-question-generation": control.open_question_generation,
    "prepare-burst": control.prepare_burst,
}


def dispatch_session_command(
    *,
    session_token: str | None,
    idempotency_key: str | None,
    workspace_id: str,
    session_id: str,
    command: str,
    expected_version: object,
    participant_user_id: str | None = None,
) -> Response:
    def work(ports: GovernedPorts, principal: Any) -> Response:
        ws = WorkspaceId(_uuid(workspace_id, "workspace_id"))
        sid = SessionId(_uuid(session_id, "session_id"))
        if (
            not isinstance(expected_version, int)
            or isinstance(expected_version, bool)
            or expected_version < 1
        ):
            raise _Rejected("EXPECTED_VERSION_REQUIRED")
        ident = _ident(idempotency_key)
        kwargs: dict[str, object] = {
            "actor": _actor(principal),
            "workspace_id": ws,
            "session_id": sid,
            "expected_session_version": expected_version,
            "ident": ident,
        }
        if command == "admit-participant":
            if not participant_user_id:
                raise _Rejected("PARTICIPANT_REQUIRED")
            kwargs["participant_user_id"] = UserId(
                _uuid(participant_user_id, "participant_user_id")
            )
            handler: Callable[..., Any] = control.admit_participant
        else:
            found = _SESSION_COMMANDS.get(command)
            if found is None:
                raise _Rejected(f"UNKNOWN_SESSION_COMMAND:{command}")
            handler = found

        def run() -> Response:
            try:
                handler(ports, **kwargs)
                replayed = False
            except control.IdempotentReplay:
                replayed = True
            # Canonical post-commit reread (never a client-assumed state).
            position = queries.session_position(ports, principal, ws, sid)
            return 200, {"kind": "committed", "replayed": replayed, "position": position}

        return _command_outcome(run)

    return _with_actor(session_token, work)


_CAPTURE_FIELDS = frozenset({"originalText", "expectedBurstVersion"})


def dispatch_capture_question(
    *,
    session_token: str | None,
    idempotency_key: str | None,
    workspace_id: str,
    session_id: str,
    original_text: object,
    expected_burst_version: object,
    extra_fields: tuple[str, ...] = (),
) -> Response:
    """CMD_CAPTURE_BURST_QUESTION. The wire contract carries ONLY the exact text
    and the Burst version the caller saw. `origin`, author, mode and every other
    field are REJECTED, never ignored: Question origin and author come from the
    verified session, never from the client (AI-origin contamination is
    unrepresentable at the API)."""

    def work(ports: GovernedPorts, principal: Any) -> Response:
        ws = WorkspaceId(_uuid(workspace_id, "workspace_id"))
        sid = SessionId(_uuid(session_id, "session_id"))
        ident = _ident(idempotency_key)
        if extra_fields:
            raise _Rejected(f"UNSUPPORTED_FIELD:{sorted(extra_fields)[0]}")
        if not isinstance(original_text, str):
            raise _Rejected("ORIGINAL_TEXT_REQUIRED")
        if (
            not isinstance(expected_burst_version, int)
            or isinstance(expected_burst_version, bool)
            or expected_burst_version < 1
        ):
            raise _Rejected("EXPECTED_VERSION_REQUIRED")

        def run() -> Response:
            question_id: str | None
            try:
                result = capture.capture_burst_question(
                    ports,
                    actor=_actor(principal),
                    workspace_id=ws,
                    session_id=sid,
                    original_text=original_text,  # verbatim, never trimmed here
                    expected_burst_version=expected_burst_version,
                    ident=ident,
                )
                replayed, question_id = False, str(result.question_id.value)
            except control.IdempotentReplay as replay:
                replayed, question_id = True, replay.result_ref
            position = queries.session_position(ports, principal, ws, sid)
            return 200, {
                "kind": "committed",
                "replayed": replayed,
                "questionId": question_id,
                "position": position,
            }

        return _command_outcome(run)

    return _with_actor(session_token, work)


def dispatch_complete_burst(
    *,
    session_token: str | None,
    idempotency_key: str | None,
    workspace_id: str,
    session_id: str,
    expected_session_version: object,
    expected_burst_version: object,
) -> Response:
    """CMD_COMPLETE_BURST (TRN-SESS-005 + TRN-BURST-005, one bundle)."""

    def work(ports: GovernedPorts, principal: Any) -> Response:
        ws = WorkspaceId(_uuid(workspace_id, "workspace_id"))
        sid = SessionId(_uuid(session_id, "session_id"))
        for version in (expected_session_version, expected_burst_version):
            if not isinstance(version, int) or isinstance(version, bool) or version < 1:
                raise _Rejected("EXPECTED_VERSION_REQUIRED")
        ident = _ident(idempotency_key)

        def run() -> Response:
            try:
                completion.complete_burst(
                    ports,
                    actor=_actor(principal),
                    workspace_id=ws,
                    session_id=sid,
                    expected_session_version=expected_session_version,  # type: ignore[arg-type]
                    expected_burst_version=expected_burst_version,  # type: ignore[arg-type]
                    ident=ident,
                )
                replayed = False
            except control.IdempotentReplay:
                replayed = True
            position = queries.session_position(ports, principal, ws, sid)
            return 200, {"kind": "committed", "replayed": replayed, "position": position}

        return _command_outcome(run)

    return _with_actor(session_token, work)


__all__ = [
    "dispatch_capture_question",
    "dispatch_complete_burst",
    "dispatch_challenge_detail",
    "dispatch_create_challenge",
    "dispatch_create_session",
    "dispatch_grant_authority",
    "dispatch_session_command",
    "dispatch_session_position",
    "dispatch_workspace_overview",
]
